options:
  substitutionOption: ALLOW_LOOSE

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/bank-sampah-backend:$SHORT_SHA',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'gcr.io/$PROJECT_ID/bank-sampah-backend:$SHORT_SHA'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy bank-sampah-backend \
        --image=gcr.io/$PROJECT_ID/bank-sampah-backend:$SHORT_SHA \
        --region=$_REGION \
        --platform=managed \
        --allow-unauthenticated \
        --set-env-vars=DB_HOST=$_DB_HOST,DB_USER=$_DB_USER,DB_PASS=$_DB_PASS,DB_NAME=$_DB_NAME
images:
- 'gcr.io/$PROJECT_ID/bank-sampah-backend:$SHORT_SHA'

substitutions:
  _DB_HOST: "YOUR_DB_HOST"
  _DB_USER: "YOUR_DB_USER"
  _DB_PASS: "YOUR_DB_PASS"
  _DB_NAME: "bank_sampah_digital"
  _REGION: "us-central1"
