// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CQkEacJvFAZYLdOr8hsfj8NbfVMdg14',
    appId: '1:50763550013:web:96400fc4101ce475844954',
    messagingSenderId: '50763550013',
    projectId: 'test-tcc-30329',
    authDomain: 'test-tcc-30329.firebaseapp.com',
    storageBucket: 'test-tcc-30329.firebasestorage.app',
    measurementId: 'G-THNRXPVZR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPb21G1VBeWvjaUYM9t06rnsB88xTsTI',
    appId: '1:50763550013:android:9d78b42b9f05d7cd844954',
    messagingSenderId: '50763550013',
    projectId: 'test-tcc-30329',
    storageBucket: 'test-tcc-30329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhUBrBq63eCte5ddQ1jBP7Pv9wh0Ks0q4',
    appId: '1:50763550013:ios:00ef4e0fd83139ad844954',
    messagingSenderId: '50763550013',
    projectId: 'test-tcc-30329',
    storageBucket: 'test-tcc-30329.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhUBrBq63eCte5ddQ1jBP7Pv9wh0Ks0q4',
    appId: '1:50763550013:ios:00ef4e0fd83139ad844954',
    messagingSenderId: '50763550013',
    projectId: 'test-tcc-30329',
    storageBucket: 'test-tcc-30329.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4CQkEacJvFAZYLdOr8hsfj8NbfVMdg14',
    appId: '1:50763550013:web:e416de3b9cd4287d844954',
    messagingSenderId: '50763550013',
    projectId: 'test-tcc-30329',
    authDomain: 'test-tcc-30329.firebaseapp.com',
    storageBucket: 'test-tcc-30329.firebasestorage.app',
    measurementId: 'G-CNFDLR7QVX',
  );
}
