// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgf-7D18TmBPWK6CewcfGV6VmHXFPvWA0',
    appId: '1:650788702738:web:b35428409a61fbdff8a6cb',
    messagingSenderId: '650788702738',
    projectId: 'prak-tcc-b8332',
    authDomain: 'prak-tcc-b8332.firebaseapp.com',
    storageBucket: 'prak-tcc-b8332.firebasestorage.app',
    measurementId: 'G-L9TRKQ4PR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ55SbZTcpWymTqgnDk2eZhK3JmFUUNzI',
    appId: '1:650788702738:android:7f79215e03cee118f8a6cb',
    messagingSenderId: '650788702738',
    projectId: 'prak-tcc-b8332',
    storageBucket: 'prak-tcc-b8332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeFCyB1Slki6_y8mqJHpDPlx4U2ikgK4',
    appId: '1:650788702738:ios:439c4b3b48a4fa8cf8a6cb',
    messagingSenderId: '650788702738',
    projectId: 'prak-tcc-b8332',
    storageBucket: 'prak-tcc-b8332.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeFCyB1Slki6_y8mqJHpDPlx4U2ikgK4',
    appId: '1:650788702738:ios:439c4b3b48a4fa8cf8a6cb',
    messagingSenderId: '650788702738',
    projectId: 'prak-tcc-b8332',
    storageBucket: 'prak-tcc-b8332.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgf-7D18TmBPWK6CewcfGV6VmHXFPvWA0',
    appId: '1:650788702738:web:87088ae8ef40b9e2f8a6cb',
    messagingSenderId: '650788702738',
    projectId: 'prak-tcc-b8332',
    authDomain: 'prak-tcc-b8332.firebaseapp.com',
    storageBucket: 'prak-tcc-b8332.firebasestorage.app',
    measurementId: 'G-0XBVBQ6NJZ',
  );

}